"""
Export diagrams to Confluence as a page hierarchy.

One *base page* holds an index; every diagram directory (a directory with a
`_manifest.yaml`) becomes a child page with the generated `.drawio` file
attached and embedded through the draw.io macro. Each page carries a
"Version" section pointing back at the git commit it was generated from, and
Confluence's own page history keeps every export as a page version.

Only the standard library is used for HTTP so DAC stays dependency-light.
Targets Confluence Cloud (REST API v2 for pages/properties, v1 for attachment
upload, which has no v2 equivalent).
"""

import base64
import hashlib
import json
import os
import subprocess
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from urllib import error, parse, request

from .converter import build_drawio_xml, find_diagram_dirs, load_mxfile, sanitize_filename

PROPERTY_KEY = "dac-export"
GENERATED_MARKER = "Generated by DAC"


class ConfluenceError(Exception):
    """Raised for any failed Confluence API call."""


# =============================================================================
# HTTP client
# =============================================================================

class ConfluenceClient:
    """
    Minimal Confluence Cloud REST client.

    `base_url` is the site root, e.g. `https://example.atlassian.net`; the
    `/wiki` context path is added automatically (override with `context`).
    Authentication is HTTP basic with an Atlassian account email + API token.
    """

    def __init__(self, base_url, user, token, context="/wiki", timeout=60):
        self.base_url = base_url.rstrip("/")
        self.context = context
        self.timeout = timeout
        creds = base64.b64encode(f"{user}:{token}".encode()).decode()
        self._auth_header = f"Basic {creds}"

    # -- low level -----------------------------------------------------------

    def _url(self, path, params=None):
        url = f"{self.base_url}{self.context}{path}"
        if params:
            url += "?" + parse.urlencode({k: v for k, v in params.items() if v is not None})
        return url

    def _request(self, method, path, params=None, json_body=None, data=None, headers=None):
        hdrs = {"Authorization": self._auth_header, "Accept": "application/json"}
        body = None
        if json_body is not None:
            body = json.dumps(json_body).encode()
            hdrs["Content-Type"] = "application/json"
        elif data is not None:
            body = data
        if headers:
            hdrs.update(headers)

        req = request.Request(self._url(path, params), data=body, method=method, headers=hdrs)
        try:
            with request.urlopen(req, timeout=self.timeout) as resp:
                raw = resp.read()
        except error.HTTPError as exc:
            detail = exc.read().decode(errors="replace")[:1000]
            raise ConfluenceError(f"{method} {path} failed: HTTP {exc.code}: {detail}") from exc
        except error.URLError as exc:
            raise ConfluenceError(f"{method} {path} failed: {exc.reason}") from exc

        if not raw:
            return None
        return json.loads(raw)

    # -- spaces / pages ------------------------------------------------------

    def get_space_id(self, space_key):
        data = self._request("GET", "/api/v2/spaces", params={"keys": space_key})
        results = data.get("results", []) if data else []
        if not results:
            raise ConfluenceError(f"Space '{space_key}' not found.")
        return results[0]["id"]

    def get_page(self, page_id):
        return self._request("GET", f"/api/v2/pages/{page_id}", params={"body-format": "storage"})

    def find_page(self, space_id, title, parent_id=None):
        """Find a page by title in a space (optionally under `parent_id`)."""
        data = self._request(
            "GET", "/api/v2/pages",
            params={"space-id": space_id, "title": title, "limit": 50},
        )
        for page in (data or {}).get("results", []):
            if parent_id is None or str(page.get("parentId")) == str(parent_id):
                return page
        return None

    def create_page(self, space_id, title, body_storage, parent_id=None):
        payload = {
            "spaceId": space_id,
            "status": "current",
            "title": title,
            "body": {"representation": "storage", "value": body_storage},
        }
        if parent_id is not None:
            payload["parentId"] = str(parent_id)
        return self._request("POST", "/api/v2/pages", json_body=payload)

    def update_page(self, page_id, title, body_storage, version_number, message=""):
        payload = {
            "id": str(page_id),
            "status": "current",
            "title": title,
            "body": {"representation": "storage", "value": body_storage},
            "version": {"number": version_number, "message": message},
        }
        return self._request("PUT", f"/api/v2/pages/{page_id}", json_body=payload)

    def page_url(self, page):
        webui = (page.get("_links") or {}).get("webui", "")
        base = (page.get("_links") or {}).get("base") or f"{self.base_url}{self.context}"
        return f"{base}{webui}"

    # -- attachments (v1: v2 has no upload endpoint) -------------------------

    def upload_attachment(self, page_id, filename, content, comment="", content_type="application/xml"):
        """Create or update an attachment on a page. `content` is bytes."""
        boundary = uuid.uuid4().hex
        parts = [
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
            f"Content-Type: {content_type}\r\n\r\n".encode() + content + b"\r\n",
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="comment"\r\n\r\n{comment}\r\n'.encode(),
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="minorEdit"\r\n\r\ntrue\r\n'.encode(),
            f"--{boundary}--\r\n".encode(),
        ]
        body = b"".join(parts)
        return self._request(
            "PUT", f"/rest/api/content/{page_id}/child/attachment",
            data=body,
            headers={
                "Content-Type": f"multipart/form-data; boundary={boundary}",
                "X-Atlassian-Token": "nocheck",
            },
        )

    # -- content properties --------------------------------------------------

    def get_property(self, page_id, key):
        data = self._request("GET", f"/api/v2/pages/{page_id}/properties", params={"key": key})
        results = (data or {}).get("results", [])
        return results[0] if results else None

    def set_property(self, page_id, key, value):
        existing = self.get_property(page_id, key)
        if existing is None:
            return self._request(
                "POST", f"/api/v2/pages/{page_id}/properties",
                json_body={"key": key, "value": value},
            )
        number = (existing.get("version") or {}).get("number", 1) + 1
        return self._request(
            "PUT", f"/api/v2/pages/{page_id}/properties/{existing['id']}",
            json_body={"key": key, "value": value, "version": {"number": number}},
        )


# =============================================================================
# Git / CI context
# =============================================================================

@dataclass
class GitContext:
    """Where the export came from; used for permalinks and version messages."""
    repo_url: str = None
    commit: str = None
    ref: str = None
    run_url: str = None
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    )

    @property
    def short_commit(self):
        return self.commit[:7] if self.commit else "unknown"

    def commit_url(self):
        if self.repo_url and self.commit:
            return f"{self.repo_url}/commit/{self.commit}"
        return None

    def tree_url(self, rel_path):
        """Permalink to a path in the repo at the exported commit."""
        if self.repo_url and self.commit:
            return f"{self.repo_url}/tree/{self.commit}/{rel_path}".rstrip("/")
        return None


def _git(args, cwd):
    try:
        return subprocess.check_output(["git", *args], cwd=cwd, stderr=subprocess.DEVNULL).decode().strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def normalize_repo_url(url):
    """Turn `git@github.com:o/r.git` / `https://github.com/o/r.git` into a browsable URL."""
    if not url:
        return None
    if url.startswith("git@"):
        host, _, path = url[4:].partition(":")
        url = f"https://{host}/{path}"
    if url.endswith(".git"):
        url = url[:-4]
    return url.rstrip("/")


def detect_git_context(repo_dir=".", repo_url=None, commit=None):
    """
    Build a GitContext from explicit values, GitHub Actions environment
    variables, or the local git checkout — in that order of preference.
    """
    env = os.environ
    if repo_url is None and env.get("GITHUB_SERVER_URL") and env.get("GITHUB_REPOSITORY"):
        repo_url = f"{env['GITHUB_SERVER_URL']}/{env['GITHUB_REPOSITORY']}"
    if repo_url is None:
        repo_url = _git(["remote", "get-url", "origin"], repo_dir)
    repo_url = normalize_repo_url(repo_url)

    commit = commit or env.get("GITHUB_SHA") or _git(["rev-parse", "HEAD"], repo_dir)
    ref = env.get("GITHUB_REF_NAME") or _git(["rev-parse", "--abbrev-ref", "HEAD"], repo_dir)

    run_url = None
    if env.get("GITHUB_RUN_ID") and repo_url:
        run_url = f"{repo_url}/actions/runs/{env['GITHUB_RUN_ID']}"

    return GitContext(repo_url=repo_url, commit=commit, ref=ref, run_url=run_url)


# =============================================================================
# Page content (Confluence storage format)
# =============================================================================

@dataclass
class DiagramSource:
    """A diagram directory resolved into a page title and draw.io XML."""
    title: str
    rel_path: str
    attachment_name: str
    xml: str
    tabs: list

    @property
    def content_hash(self):
        return hashlib.sha256(self.xml.encode()).hexdigest()


def _link(url, text):
    return f'<a href="{escape(url, quote=True)}">{escape(text)}</a>' if url else escape(text)


def _version_table(ctx, rows):
    cells = "".join(f"<tr><th>{escape(k)}</th><td>{v}</td></tr>" for k, v in rows)
    return f"<h2>Version</h2><table><tbody>{cells}</tbody></table>"


def _generated_note(ctx):
    return (
        '<ac:structured-macro ac:name="info"><ac:rich-text-body>'
        f"<p>{GENERATED_MARKER} from commit <code>{escape(ctx.short_commit)}</code>. "
        "Do not edit this page by hand: it is overwritten on every export.</p>"
        "</ac:rich-text-body></ac:structured-macro>"
    )


def diagram_page_body(source, ctx):
    """Storage-format body for a diagram page."""
    name = escape(source.attachment_name)
    macro = (
        '<ac:structured-macro ac:name="drawio" ac:schema-version="1">'
        f'<ac:parameter ac:name="diagramName">{name}</ac:parameter>'
        f'<ac:parameter ac:name="attachment">{name}</ac:parameter>'
        '<ac:parameter ac:name="pageSize">false</ac:parameter>'
        '<ac:parameter ac:name="lbox">true</ac:parameter>'
        "</ac:structured-macro>"
    )
    tabs = "".join(f"<li>{escape(t)}</li>" for t in source.tabs)
    rows = [
        ("Commit", _link(ctx.commit_url(), ctx.short_commit)),
        ("Branch / ref", escape(ctx.ref or "unknown")),
        ("Source", _link(ctx.tree_url(source.rel_path), source.rel_path)),
        ("Generated", escape(ctx.generated_at)),
    ]
    if ctx.run_url:
        rows.append(("Workflow run", _link(ctx.run_url, ctx.run_url)))
    rows.append(("Content hash", f"<code>{source.content_hash[:12]}</code>"))
    return (
        _generated_note(ctx)
        + macro
        + _version_table(ctx, rows)
        + f"<h2>Diagram tabs</h2><ul>{tabs}</ul>"
        + "<p>Download the draw.io file: "
        f'<ac:link><ri:attachment ri:filename="{name}" /></ac:link></p>'
    )


def index_page_body(entries, ctx):
    """Storage-format body for the base page: a table of all diagram pages."""
    rows = "".join(
        "<tr>"
        f'<td><ac:link><ri:page ri:content-title="{escape(e["title"], quote=True)}" /></ac:link></td>'
        f"<td>{_link(ctx.tree_url(e['rel_path']), e['rel_path'])}</td>"
        f"<td>{e['tabs']}</td>"
        f"<td>{escape(e['status'])}</td>"
        "</tr>"
        for e in entries
    )
    table = (
        "<table><tbody><tr><th>Diagram</th><th>Source</th><th>Tabs</th><th>Last export</th></tr>"
        f"{rows}</tbody></table>"
    )
    version_rows = [
        ("Commit", _link(ctx.commit_url(), ctx.short_commit)),
        ("Branch / ref", escape(ctx.ref or "unknown")),
        ("Generated", escape(ctx.generated_at)),
    ]
    if ctx.run_url:
        version_rows.append(("Workflow run", _link(ctx.run_url, ctx.run_url)))
    return _generated_note(ctx) + "<h2>Diagrams</h2>" + table + _version_table(ctx, version_rows)


# =============================================================================
# Export
# =============================================================================

@dataclass
class ExportResult:
    base_page_id: str = None
    base_page_url: str = None
    created: list = field(default_factory=list)
    updated: list = field(default_factory=list)
    skipped: list = field(default_factory=list)
    built: list = field(default_factory=list)

    @property
    def changed(self):
        return bool(self.created or self.updated)


def repo_root_for(path):
    """The git top-level directory containing `path`, or `path`'s parent when not in git."""
    top = _git(["rev-parse", "--show-toplevel"], str(path))
    return Path(top) if top else Path(path).resolve().parent


def collect_diagrams(root, title_prefix="", repo_root=None):
    """
    Turn every diagram directory under `root` into a DiagramSource. `rel_path`
    is relative to `repo_root` (default: the git top-level) so permalinks work.
    """
    root = Path(root)
    repo_root = Path(repo_root) if repo_root else repo_root_for(root)
    sources = []
    for d in find_diagram_dirs(root):
        _, manifest = load_mxfile(d)
        rel = Path(os.path.relpath(d.resolve(), repo_root.resolve())).as_posix()
        sources.append(DiagramSource(
            title=f"{title_prefix}{d.name}",
            rel_path=rel,
            attachment_name=f"{sanitize_filename(d.name)}.drawio",
            xml=build_drawio_xml(d),
            tabs=[x["name"] for x in manifest.get("diagrams", [])],
        ))
    return sources


def _resolve_base_page(client, base_page_id, space_key, base_title, parent_page_id, ctx, dry_run, log):
    """Return (base_page dict, space_id, created: bool)."""
    if base_page_id:
        page = client.get_page(base_page_id)
        return page, page["spaceId"], False

    if not (space_key and base_title):
        raise ConfluenceError("Either a base page id or a space key + base page title is required.")

    space_id = client.get_space_id(space_key)
    page = client.find_page(space_id, base_title, parent_page_id)
    if page:
        return page, space_id, False

    log(f"  + base page '{base_title}' does not exist; creating")
    if dry_run:
        return {"id": "dry-run", "title": base_title, "version": {"number": 0}, "_links": {}}, space_id, True
    page = client.create_page(space_id, base_title, index_page_body([], ctx), parent_page_id)
    return page, space_id, True


def export_to_confluence(
    client,
    root,
    *,
    base_page_id=None,
    space_key=None,
    base_title=None,
    parent_page_id=None,
    title_prefix="",
    ctx=None,
    force=False,
    dry_run=False,
    update_index=True,
    out_dir=None,
    repo_root=None,
    log=print,
):
    """
    Export every diagram directory under `root` to Confluence.

    - Diagram pages are children of the base page, titled after the directory
      (with `title_prefix`). Pages are created if missing, updated only when
      the generated draw.io content changed (or `force`), and never deleted.
    - The base page body is replaced with an index unless `update_index` is
      False.
    - `out_dir`, if given, also receives the generated `.drawio` files (handy
      for CI artifacts).
    - `dry_run` performs reads only and logs what would change.
    """
    ctx = ctx or detect_git_context(root)
    result = ExportResult()
    sources = collect_diagrams(root, title_prefix, repo_root)
    if not sources:
        raise ConfluenceError(f"No diagram directories (with _manifest.yaml) found under {root}/")

    if out_dir:
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        for s in sources:
            path = out_dir / s.attachment_name
            path.write_text(s.xml)
            result.built.append(str(path))

    base_page, space_id, base_created = _resolve_base_page(
        client, base_page_id, space_key, base_title, parent_page_id, ctx, dry_run, log
    )
    base_id = base_page["id"]
    result.base_page_id = base_id
    result.base_page_url = client.page_url(base_page)
    message = f"DAC export from {ctx.short_commit}"
    index_entries = []

    for s in sources:
        existing = None if base_created else client.find_page(space_id, s.title, base_id)
        body = diagram_page_body(s, ctx)
        prop_value = {
            "hash": s.content_hash,
            "commit": ctx.commit,
            "generated_at": ctx.generated_at,
            "source": s.rel_path,
        }

        if existing is None:
            log(f"  + create '{s.title}'")
            result.created.append(s.title)
            status = f"created @ {ctx.short_commit}"
            if not dry_run:
                page = client.create_page(space_id, s.title, body, base_id)
                client.upload_attachment(page["id"], s.attachment_name, s.xml.encode(), message)
                client.set_property(page["id"], PROPERTY_KEY, prop_value)
        else:
            prop = client.get_property(existing["id"], PROPERTY_KEY)
            previous = (prop or {}).get("value") or {}
            if previous.get("hash") == s.content_hash and not force:
                log(f"  = unchanged '{s.title}' (last export {previous.get('commit', '?')[:7]})")
                result.skipped.append(s.title)
                status = f"unchanged since {previous.get('commit', '?')[:7]}"
            else:
                log(f"  ~ update '{s.title}'")
                result.updated.append(s.title)
                status = f"updated @ {ctx.short_commit}"
                if not dry_run:
                    client.upload_attachment(existing["id"], s.attachment_name, s.xml.encode(), message)
                    version = existing["version"]["number"] + 1
                    client.update_page(existing["id"], s.title, body, version, message)
                    client.set_property(existing["id"], PROPERTY_KEY, prop_value)

        index_entries.append({
            "title": s.title, "rel_path": s.rel_path, "tabs": len(s.tabs), "status": status,
        })

    if update_index and (result.changed or base_created or force):
        log(f"  ~ update index on base page '{base_page.get('title', base_id)}'")
        if not dry_run:
            # Re-read for the current version number: creating children doesn't
            # bump it, but a previous run in the same second might have.
            current = client.get_page(base_id)
            version = current["version"]["number"] + 1
            client.update_page(base_id, current["title"], index_page_body(index_entries, ctx), version, message)

    return result
